import json
from pathlib import Path

OUT = Path("data/round2/train_hard.jsonl")
OUT.parent.mkdir(parents=True, exist_ok=True)

SYSTEM = (
    "You are TaskMind. Read the team WhatsApp message and return ONLY a JSON "
    "object with these exact fields: intent (TASK_ASSIGN / TASK_DONE / "
    "TASK_UPDATE / PROGRESS_NOTE / GENERAL_MESSAGE), assigneeName, project, "
    "title, deadline, priority, progressPercent. Use null for unknown fields."
)


def row(message, intent, assignee=None, project=None, title=None,
        deadline=None, priority=None, progress=None):
    output = {
        "intent": intent,
        "assigneeName": assignee,
        "project": project,
        "title": title,
        "deadline": deadline,
        "priority": priority,
        "progressPercent": progress,
    }
    out_str = json.dumps(output, ensure_ascii=False)
    prompt = f"### System:\n{SYSTEM}\n\n### Message:\n{message}"
    completion = f"\n\n### Response:\n{out_str}"
    return {"prompt": prompt, "completion": completion,
            "text": prompt + completion}


samples = []

# ── CAT 1: TASK_ASSIGN with "complete/finish/build" verbs (45 examples) ─────
# These are the exact failure: model outputs TASK_DONE when it sees "complete"
# Key signal: @mention + future imperative = TASK_ASSIGN, not TASK_DONE
samples += [
    row("@Arpit please complete the dashboard by Friday",
        "TASK_ASSIGN", "Arpit", None, "Complete dashboard", "Friday", "normal"),
    row("@Neha complete the onboarding flow this sprint",
        "TASK_ASSIGN", "Neha", None, "Complete onboarding flow", None, "normal"),
    row("@Agrim please complete the admin panel ASAP",
        "TASK_ASSIGN", "Agrim", None, "Complete admin panel", None, "urgent"),
    row("@Rohan please complete the dashboard redesign",
        "TASK_ASSIGN", "Rohan", None, "Complete dashboard redesign", None, "normal"),
    row("@Nisha please complete the auth service before release",
        "TASK_ASSIGN", "Nisha", None, "Complete auth service", None, "high"),
    row("@Sumit please complete the search feature this week",
        "TASK_ASSIGN", "Sumit", None, "Complete search feature", None, "normal"),
    row("@Priya complete the wireframes by EOD",
        "TASK_ASSIGN", "Priya", None, "Complete wireframes", "EOD", "normal"),
    row("@Dev please finish the API integration today",
        "TASK_ASSIGN", "Dev", None, "Finish API integration", "today", "urgent"),
    row("@Shiv finish the payment module by tomorrow",
        "TASK_ASSIGN", "Shiv", None, "Finish payment module", "tomorrow", "high"),
    row("@Karan can you complete the unit tests for auth",
        "TASK_ASSIGN", "Karan", None, "Complete unit tests for auth", None, "normal"),
    row("@Rahul please finish the backend API by tonight",
        "TASK_ASSIGN", "Rahul", None, "Finish backend API", "tonight", "high"),
    row("@Meera complete the user research report this week",
        "TASK_ASSIGN", "Meera", None, "Complete user research report", None, "normal"),
    row("@Ankit please complete the mobile responsive fixes",
        "TASK_ASSIGN", "Ankit", None, "Complete mobile responsive fixes", None, "normal"),
    row("@Pooja finish the release notes for v2.1",
        "TASK_ASSIGN", "Pooja", None, "Finish release notes v2.1", None, "normal"),
    row("@Vijendra please complete the deployment scripts",
        "TASK_ASSIGN", "Vijendra", None, "Complete deployment scripts", None, "normal"),
    row("@Sahil complete the GraphQL resolvers by Thursday",
        "TASK_ASSIGN", "Sahil", None, "Complete GraphQL resolvers", "Thursday", "normal"),
    row("@team please complete the sprint review doc before 5pm",
        "TASK_ASSIGN", None, None, "Complete sprint review doc", "5pm", "normal"),
    row("@Rohan please complete the notifications module ASAP",
        "TASK_ASSIGN", "Rohan", None, "Complete notifications module", None, "urgent"),
    row("@Aditya finish the Redis cache setup before launch",
        "TASK_ASSIGN", "Aditya", None, "Finish Redis cache setup", None, "high"),
    row("@Riya please complete the E2E test suite this sprint",
        "TASK_ASSIGN", "Riya", None, "Complete E2E test suite", None, "normal"),
    row("@Himanshu finish the Kubernetes migration configs",
        "TASK_ASSIGN", "Himanshu", None, "Finish Kubernetes migration configs", None, "normal"),
    row("@Jatin please complete the Slack integration this week",
        "TASK_ASSIGN", "Jatin", None, "Complete Slack integration", None, "normal"),
    row("@Gaurav finish the checkout flow bug fix today",
        "TASK_ASSIGN", "Gaurav", None, "Fix checkout flow bug", "today", "urgent"),
    row("@Divya please complete the empty state designs by Friday",
        "TASK_ASSIGN", "Divya", None, "Complete empty state designs", "Friday", "normal"),
    row("@Tarun finish the analytics dashboard this sprint",
        "TASK_ASSIGN", "Tarun", None, "Finish analytics dashboard", None, "normal"),
    row("@Vishal complete the Grafana alerting setup",
        "TASK_ASSIGN", "Vishal", None, "Complete Grafana alerting setup", None, "normal"),
    row("@Ankur please finish the monitoring dashboard for prod",
        "TASK_ASSIGN", "Ankur", None, "Finish monitoring dashboard", None, "high"),
    row("@Bhavya complete the form validation for settings page",
        "TASK_ASSIGN", "Bhavya", None, "Complete form validation", None, "normal"),
    row("@Suresh finish the README update with deployment steps",
        "TASK_ASSIGN", "Suresh", None, "Finish README update", None, "normal"),
    row("@Nikhil please complete the task tracker integration",
        "TASK_ASSIGN", "Nikhil", None, "Complete task tracker integration", None, "normal"),
    row("@Harshit finish the docker-compose updates by EOD",
        "TASK_ASSIGN", "Harshit", None, "Finish docker-compose update", "EOD", "normal"),
    row("@Deepak please complete the k8s deployment configs",
        "TASK_ASSIGN", "Deepak", None, "Complete k8s deployment configs", None, "normal"),
    row("@Siddharth complete the seed data for QA environment",
        "TASK_ASSIGN", "Siddharth", None, "Complete QA seed data", None, "normal"),
    row("@Pallavi finish the test data setup before the demo",
        "TASK_ASSIGN", "Pallavi", None, "Finish test data setup", None, "high"),
    row("@Pranav please complete the investigation on /orders spike",
        "TASK_ASSIGN", "Pranav", None, "Investigate /orders error spike", None, "urgent"),
    row("@Isha finish the authentication flow documentation",
        "TASK_ASSIGN", "Isha", None, "Document authentication flow", None, "normal"),
    row("@Vaibhav complete the user data migration script",
        "TASK_ASSIGN", "Vaibhav", None, "Complete user data migration", None, "high"),
    row("@Chetan please complete the SSO integration backend",
        "TASK_ASSIGN", "Chetan", None, "Complete SSO integration backend", None, "normal"),
    row("@Nitin finish fixing the Jenkins builds before standup",
        "TASK_ASSIGN", "Nitin", None, "Fix Jenkins build failures", None, "urgent"),
    row("@Tushar complete the Razorpay refund API integration",
        "TASK_ASSIGN", "Tushar", None, "Complete Razorpay refund API", None, "normal"),
    row("@Sonali please finish the release notes for version 2.1.0",
        "TASK_ASSIGN", "Sonali", None, "Finish release notes 2.1.0", None, "normal"),
    row("@Rishabh complete the GraphQL schema migration",
        "TASK_ASSIGN", "Rishabh", None, "Complete GraphQL schema migration", None, "normal"),
    row("@Varsha please complete the E2E test scripts for checkout",
        "TASK_ASSIGN", "Varsha", None, "Complete checkout E2E tests", None, "normal"),
    row("@Yash please complete the SQL query optimisation in reports",
        "TASK_ASSIGN", "Yash", None, "Optimise SQL queries in reports", None, "normal"),
    row("@Saurabh finish the new test environment setup by Monday",
        "TASK_ASSIGN", "Saurabh", None, "Set up new test environment", "Monday", "normal"),
]

# ── CAT 2: TASK_UPDATE with percentage (30 examples) ─────────────────────────
# "X% done/complete/ho gaya" WITHOUT a past-tense completion = TASK_UPDATE
samples += [
    row("notification service 60% done",
        "TASK_UPDATE", None, None, "Notification service", None, None, 60),
    row("DB migration 75% done",
        "TASK_UPDATE", None, None, "DB migration", None, None, 75),
    row("checkout flow 80% complete",
        "TASK_UPDATE", None, None, "Checkout flow", None, None, 80),
    row("login module 50% ho gaya",
        "TASK_UPDATE", None, None, "Login module", None, None, 50),
    row("search feature 40% done",
        "TASK_UPDATE", None, None, "Search feature", None, None, 40),
    row("payment module 70% complete",
        "TASK_UPDATE", None, None, "Payment module", None, None, 70),
    row("admin panel 90% done, just final testing left",
        "TASK_UPDATE", None, None, "Admin panel", None, None, 90),
    row("onboarding flow 65% ho gaya",
        "TASK_UPDATE", None, None, "Onboarding flow", None, None, 65),
    row("analytics dashboard 55% done",
        "TASK_UPDATE", None, None, "Analytics dashboard", None, None, 55),
    row("API integration 85% complete",
        "TASK_UPDATE", None, None, "API integration", None, None, 85),
    row("auth service 30% ho gaya",
        "TASK_UPDATE", None, None, "Auth service", None, None, 30),
    row("frontend 45% done, desktop view complete, mobile pending",
        "TASK_UPDATE", None, None, "Frontend", None, None, 45),
    row("user onboarding 20% done",
        "TASK_UPDATE", None, None, "User onboarding", None, None, 20),
    row("dashboard redesign 35% ho gaya",
        "TASK_UPDATE", None, None, "Dashboard redesign", None, None, 35),
    row("billing module 60% complete, still 3 edge cases left",
        "TASK_UPDATE", None, None, "Billing module", None, None, 60),
    row("Redis cache setup 50% done",
        "TASK_UPDATE", None, None, "Redis cache setup", None, None, 50),
    row("k8s migration 40% complete, 3 services moved",
        "TASK_UPDATE", None, None, "Kubernetes migration", None, None, 40),
    row("reports module 75% ho gaya, almost there",
        "TASK_UPDATE", None, None, "Reports module", None, None, 75),
    row("mobile app 25% done, just started",
        "TASK_UPDATE", None, None, "Mobile app", None, None, 25),
    row("GraphQL resolvers 65% done",
        "TASK_UPDATE", None, None, "GraphQL resolvers", None, None, 65),
    row("SSO integration 70% complete, IDP config remaining",
        "TASK_UPDATE", None, None, "SSO integration", None, None, 70),
    row("dark mode feature 50% ho gaya",
        "TASK_UPDATE", None, None, "Dark mode feature", None, None, 50),
    row("E2E test suite 80% done",
        "TASK_UPDATE", None, None, "E2E test suite", None, None, 80),
    row("email templates 60% complete",
        "TASK_UPDATE", None, None, "Email templates", None, None, 60),
    row("vendor API integration 45% done",
        "TASK_UPDATE", None, None, "Vendor API integration", None, None, 45),
    row("CI pipeline optimisation 30% ho gaya",
        "TASK_UPDATE", None, None, "CI pipeline optimisation", None, None, 30),
    row("push notifications 55% done",
        "TASK_UPDATE", None, None, "Push notifications", None, None, 55),
    row("deployment scripts 80% complete",
        "TASK_UPDATE", None, None, "Deployment scripts", None, None, 80),
    row("schema migration 60% ho gaya",
        "TASK_UPDATE", None, None, "Schema migration", None, None, 60),
    row("feature flags setup 90% done, just prod config left",
        "TASK_UPDATE", None, None, "Feature flags setup", None, None, 90),
]

# ── CAT 3: GENERAL_MESSAGE — social / non-task (45 examples) ─────────────────
# Social, casual, greetings, appreciation, logistics — NOT task-related
samples += [
    row("bhai kaafi solid kaam kiya tune", "GENERAL_MESSAGE"),
    row("have a good weekend everyone!", "GENERAL_MESSAGE"),
    row("please add me to the meeting invite", "GENERAL_MESSAGE"),
    row("let's discuss in sprint planning", "GENERAL_MESSAGE"),
    row("checking in — everyone aligned?", "GENERAL_MESSAGE"),
    row("good morning team!", "GENERAL_MESSAGE"),
    row("thanks for the review!", "GENERAL_MESSAGE"),
    row("great work on the release everyone", "GENERAL_MESSAGE"),
    row("zoom link?", "GENERAL_MESSAGE"),
    row("who's joining the retro today?", "GENERAL_MESSAGE"),
    row("koi nahi bhai, ho jayega", "GENERAL_MESSAGE"),
    row("roger that", "GENERAL_MESSAGE"),
    row("noted, will follow up", "GENERAL_MESSAGE"),
    row("congrats on the promotion!", "GENERAL_MESSAGE"),
    row("can someone share the figma link?", "GENERAL_MESSAGE"),
    row("kal chutti hai team", "GENERAL_MESSAGE"),
    row("LOL 😂 that was unexpected", "GENERAL_MESSAGE"),
    row("okay noted", "GENERAL_MESSAGE"),
    row("please don't push to main directly", "GENERAL_MESSAGE"),
    row("anyone on call this weekend?", "GENERAL_MESSAGE"),
    row("is the retro still at 5pm?", "GENERAL_MESSAGE"),
    row("please update your timesheets everyone", "GENERAL_MESSAGE"),
    row("team lunch at 1pm tomorrow", "GENERAL_MESSAGE"),
    row("can we get access to the staging environment?", "GENERAL_MESSAGE"),
    row("meeting rescheduled to 4pm", "GENERAL_MESSAGE"),
    row("apologies for the delay", "GENERAL_MESSAGE"),
    row("I'll be OOO tomorrow, Arpit will cover", "GENERAL_MESSAGE"),
    row("glad we got that resolved!", "GENERAL_MESSAGE"),
    row("what time is the client call?", "GENERAL_MESSAGE"),
    row("happy friday team! 🎉", "GENERAL_MESSAGE"),
    row("can we push today's release to tomorrow?", "GENERAL_MESSAGE"),
    row("please add comments to this PR, it's unclear", "GENERAL_MESSAGE"),
    row("bhai chai pi ke aao, fir discuss karte hain", "GENERAL_MESSAGE"),
    row("where are the API docs?", "GENERAL_MESSAGE"),
    row("interesting, didn't know that!", "GENERAL_MESSAGE"),
    row("I agree with Rohan's approach here", "GENERAL_MESSAGE"),
    row("any thoughts on using Redis for this?", "GENERAL_MESSAGE"),
    row("sent the credentials to your email", "GENERAL_MESSAGE"),
    row("ping me when you're free", "GENERAL_MESSAGE"),
    row("see you all in standup", "GENERAL_MESSAGE"),
    row("thoda rush ho gaya aaj", "GENERAL_MESSAGE"),
    row("kal discuss karte hain", "GENERAL_MESSAGE"),
    row("who is the DRI for the payment module?", "GENERAL_MESSAGE"),
    row("I pushed a draft PR for early feedback", "GENERAL_MESSAGE"),
    row("all good, no action needed from my side", "GENERAL_MESSAGE"),
]

# ── CAT 4: PROGRESS_NOTE — metrics, standups, status reports (40 examples) ───
# Objective status updates, metrics, team reports — not an assignment or task done
samples += [
    row("load test: DB migration stable at 800 rps",
        "PROGRESS_NOTE", None, None, "DB migration load test", None, None, None),
    row("A/B test result on checkout: variant B wins by 12%",
        "PROGRESS_NOTE", None, None, "Checkout A/B test", None, None, None),
    row("team: Rohan on leave this week, Priya covering his tasks",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("standup: worked on auth yesterday, continuing today",
        "PROGRESS_NOTE", None, None, "Auth module", None, None, None),
    row("EOD update: completed 3 stories, 1 in progress",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("sprint status: 60% tasks done, on track for Friday",
        "PROGRESS_NOTE", None, None, None, None, None, 60),
    row("prod CPU spiked to 90% at midnight, reverted config change",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("weekly update: shipped search feature, started on analytics",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("release v2.1 scheduled for Thursday, all features frozen",
        "PROGRESS_NOTE", None, None, "Release v2.1", "Thursday", None, None),
    row("daily standup: no blockers, on track for sprint goals",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("prod deploy completed at 11pm, all health checks passing",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("error rate dropped from 2% to 0.1% after the fix",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("team velocity this sprint: 42 story points, up from 35",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("retro highlights: need better staging env, comms improved",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("API response time improved 40% after caching",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("user signups up 20% this week after onboarding changes",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("security audit findings: 2 criticals, 5 high, all assigned",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("disk usage hit 85%, cleanup scheduled for tonight",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("today we crossed 100k API requests milestone",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("release postponed 2 days due to QA findings",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("infra cost this month: $3400, down 15% from last month",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("postmortem for last night's outage: root cause was misconfigured timeout",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("user churn is down 8% this month after the onboarding changes",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("yesterday: wrote tests. today: code review and bug fixes",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("rollout to 10% of users complete, monitoring metrics",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("p99 latency is 320ms, target is 500ms — we're good",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("code coverage improved from 62% to 78% this sprint",
        "PROGRESS_NOTE", None, None, None, None, None, 78),
    row("push notification delivery rate improved to 96%",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("sprint review done, client happy with the demo",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("all 3 environments stable after yesterday's migration",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("model accuracy improved from 88% to 93% after retraining",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("daily metrics: 2.3k active users, 99.8% uptime",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("load test result: system stable at 800 rps, degraded at 1200",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("site went down for 2 minutes at 3pm, auto-recovered",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("CI pipeline now runs 30% faster after parallelization",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("regression test pass rate: 94.5%, 12 flaky tests identified",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("as of sprint day 7: 8 of 12 stories done, 4 in progress",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("memory usage trending up in prod, investigating root cause",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("A/B test on login flow: new design 15% better conversion",
        "PROGRESS_NOTE", None, None, None, None, None, None),
    row("server costs reduced by 22% after switching to spot instances",
        "PROGRESS_NOTE", None, None, None, None, None, None),
]

# ── CAT 5: TASK_DONE — clear past-tense explicit completions (20 examples) ───
# These reinforce that TASK_DONE = past-tense, no @ assignment, no percentage
samples += [
    row("auth service done, pushed to staging",
        "TASK_DONE", None, None, "Auth service", None, None, None),
    row("onboarding flow is complete and live in prod",
        "TASK_DONE", None, None, "Onboarding flow", None, None, None),
    row("admin panel shipped, all features working",
        "TASK_DONE", None, None, "Admin panel", None, None, None),
    row("search feature merged and deployed",
        "TASK_DONE", None, None, "Search feature", None, None, None),
    row("dashboard redesign is done and live",
        "TASK_DONE", None, None, "Dashboard redesign", None, None, None),
    row("payment module is complete, tested on staging",
        "TASK_DONE", None, None, "Payment module", None, None, None),
    row("notifications are live in production",
        "TASK_DONE", None, None, "Notifications", None, None, None),
    row("mobile responsive issues fixed and verified",
        "TASK_DONE", None, None, "Mobile responsive fixes", None, None, None),
    row("DB migration complete, tested successfully",
        "TASK_DONE", None, None, "DB migration", None, None, None),
    row("E2E tests done, all 20 scenarios passing",
        "TASK_DONE", None, None, "E2E tests", None, None, None),
    row("GraphQL schema migration completed without downtime",
        "TASK_DONE", None, None, "GraphQL schema migration", None, None, None),
    row("Redis cache is set up and live, seeing 60% latency drop",
        "TASK_DONE", None, None, "Redis cache setup", None, None, None),
    row("k8s deployment configs updated and applied",
        "TASK_DONE", None, None, "K8s deployment configs", None, None, None),
    row("SSO integration done and tested with all IDP flows",
        "TASK_DONE", None, None, "SSO integration", None, None, None),
    row("dark mode is shipped in the latest release",
        "TASK_DONE", None, None, "Dark mode", None, None, None),
    row("Grafana alerts configured and firing correctly",
        "TASK_DONE", None, None, "Grafana alerts", None, None, None),
    row("API documentation updated and published",
        "TASK_DONE", None, None, "API documentation", None, None, None),
    row("Razorpay webhook retry logic implemented and live",
        "TASK_DONE", None, None, "Razorpay webhook retry", None, None, None),
    row("feature flags setup complete, A/B test is live",
        "TASK_DONE", None, None, "Feature flags", None, None, None),
    row("audit logs for admin actions are implemented and deployed",
        "TASK_DONE", None, None, "Audit logs", None, None, None),
]

with open(OUT, "w", encoding="utf-8") as f:
    for s in samples:
        f.write(json.dumps(s, ensure_ascii=False) + "\n")

from collections import Counter
counts = Counter(json.loads(l)["completion"].split('"intent": "')[1].split('"')[0]
                 for l in OUT.read_text().splitlines())
print(f"Generated {len(samples)} hard-negative examples → {OUT}")
print("\nIntent distribution:")
for k, v in sorted(counts.items()):
    print(f"  {k:<20} {v}")
